### ISSUE TITLE
TypeError: features.mmul is not a function

### ISSUE THREAD

**Issue by tommedema** [mljs/logistic-regression#3]
This is the only binary logistic regression library I could find in Javascript / Node. If there are any more maintained ones that I am unaware of, please let me know.

I just installed this library and created a simple function:

```
import { Matrix } from 'ml-matrix'
import LogisticRegression from 'ml-logistic-regression'

export const predictBinaryLogistic = (
  xs: number[][], // tslint:disable-line
  ys: number[]
): number[] => {
  const mx = new Matrix(xs)
  const my = Matrix.columnVector(ys)

  const reg = new LogisticRegression(1000, 5e-3)
  reg.train(mx, my)

  const results = reg.predict(xs)

  return results
}
```

I test it like so:

```
import { predictBinary Logistic } from '../src'

describe('predict', () => {
  it('should predict with real xs and binary ys', () => {
    const xs = [[0, 0], [0, 1], [1, 0], [1, 1]]
    const ys = [0, 1, 1, 0]

    const results = predictBinaryLogistic(RegressMethod.binaryLogistic, xs, ys)

    console.log(results)
  })
})
```

But get:

```
  1) predict
       should predict with real xs and binary ys:
     TypeError: features.mmul is not a function
      at LogisticRegressionTwoClasses.testScores (project/node_modules/ml-logistic-regression/lib/logreg.js:31:34)
      at LogisticRegression.predict project/node_modules/ml-logistic-regression/lib/logreg.js:103:54)
      at Object.exports.predictBinaryLogistic (src/methods/binaryLogistic.ts:21:23)
      at Object.exports.predict (src/regress.ts:37:14)
      at Context.it (test/index.ts:10:21)
```

**Comment by tommedema** [comment]
There was a typo

`const results = reg.predict(xs)`

should be

`const results = reg.predict(mx)`
