### ISSUE TITLE
ReferenceError: LogisticRegression is not defined

### ISSUE THREAD

**Issue by yuta-vet** [mljs/logistic-regression#8]
When I run the example script in README.md, I got this error. 
ReferenceError: LogisticRegression is not defined
    at Object.<anonymous> (C:\Users\test.js:22:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

How can I fix it?

**Comment by targos** [comment]
Example is fixed
